
= TT05 I2C (BERT) Bit Error Rate Tester / Echo ALU Peripheral

Notes on TT05 submission (04 Nov 2023):

* config.tcl has CLOCK_PERIOD="15" (ns) for STA reporting against 66.66MHz.

* STA report was clean all but 4 'max slew' in Slowest corner, all 4 VIOLATIONs just
	+0.01ns over 0.75 reporting limit, less than 1.25% over limit.  The max transition
	(from liberty cell characteristics) is 1.5ns so well within cell limits.
    This slew matters was not an issue for TT.
	So this was considered benign for this project, even if I get to
	clock it at 66Mhz.


I start this project around 10 days before, the main project is in SpinalHDL
and I did have an outline I2C implementation to work from (that had not been
tested/verified at the time).  The original I2C implementation was designed
around being a CPU debug port function over a single communications wire.
It was to be I2C like but would be ok to adapt things to the specific
circumstance that needed.  So the result is this something that looks like I2C
to me in a VCD image but it has not even been tested against a real I2C controller.

An amount of time was spent hung up on GL simulation X propagation matters as it
was not testing well.  I only found the real cause of the issue in the final few
hours (a copy-and-paste typo).  Once this was resolved it showed up two main areas
of concern I could manage in the test-benches.

The project doesn't particularly need a specific master clock rate, and part
of the design requirements are to allow the variable master clock rate to be tested
for  error and capture rates in the range of speeds traditional I2C operates.

I did not have time to pay special attention to trying to achieve maximum
I2C clock rate to master clock rate ratios.  Only 1:3 has succeeded in
test-benches, most of the debugging was done at and around 1:6.


Due to adding the ALU read and RECV changes in the last few days, it appears
after reviewing data my intention was it to be an ALU(read) operation and
not a RECV operation.  So the RECV now performs ADD1 while the ALU(read)
repeats the value.  The intention was to have ALU(read) have 4 modes, repeat
accumulator value, rotate-left-accumulator, invert-accumulator,
add-one-and-accumulate).  So this will have to be corrected in the future.

The AUTOBAUD and STRETCH features did not make it, the commands exist and a best-effort
first implementation exists in the code, due to time constraints,
I spent the time checking a validating the SEL_MODE (noise immunity filters).



With the test-bench a number of options exist to try to cover as much ground as
possible:

```bash
# standard iverlog/cocotb with defaults
cd src
make clean
make
# standard verilator/cocotb with defaults
make clean
SIM=verilator make

# standard iverilog/cocotb gate level testing (needs tt_um_dlmiles_tt05_i2c_bert.v from flow)
# delay-1 gate-level simulation
make clean
GATES=yes make

make clean
# SDF gate-level simulation (TODO needs tt_um_dlmiles_tt05_i2c_bert.v and *.sdf file from flow)
SIM=cvc make
```

On top of these 3 main method to simulate, the 2-state (Verilator) and the
gate-level simulations, you can specify a policy for initial random state (this is particularly useful when using iverilog to remove X states on startup that do not exist in any real IC)

```
# This will assign the logic value 1 to X state
make clean
RANDOM_POLICY=one make

# This will assign the logic value 0 to X state
make clean
RANDOM_POLICY=zero make

# This will assign a random logic state of 0 or 1 to X state, this is based on the
#  RANDOM_SEED value and hierarchy path of the specific signal being modified, in an
#  attempt to be both random and reproducable
make clean
RANDOM_POLICY=random make
```

On top of these there are then a number of options to change the simulation
circumstances under test:

```
# open-drain I2C line signalling - this is the default
PUSH_PULL_MODE=false

# push-pull I2C line signalling
PUSH_PULL_MODE=true

# SCL and SDA source filter mode (0 is default)
SCL_MODE=0

# timer endstop setting on power-up (inverted, so 0 means 12bit max of 4095)
DIV12=0


# The number of global clock cycles per SDA bit width
# (smaller numbers means higher I2C bandwidth,
#     3 is the minimum seen working under test)
# The default is setup for assuming 10MHz and wanting I2C fast-mode (400kbps)
#     a kind of middle of the middle expectations on
#     both sides (system clock frequency and I2C bandwidth)
# Values that are odd numbered result in the test-bench using half-cycles
#     (negative edge / fall transitions) for the
CYCLES_PER_BIT=28

```

I can say a number of combinations of these operating parameters were tested
so there is a high chance of success.  By submission time I had not had
time to integrate into github actions a CI maxtrix of scenarios to test.


== TODO

Have a mode to disable the timeoutError condition.  Need to test that a STOP
sequence will force it to reset, so the controller has a mechanism (that
does not involve a hardware reset) to bring.  With this the timeoutError
can be entire optional ?

Revert the timeout timer back into the original design goal for an auto-baud
with clockless (no SCL) line version of I2C.  This is an area to explore in
the future a 1-wire version of I2C for a point-to-point setup (1 controller, 1
peripheral)

Rename SCL_MODE to FILTER_MODE
Rename DIV12 to timeout

Add more filter modes:

* ANDNOR2-unanimous
* DFF2-synchronizer
* DFF4-synchronizer


Implement CYCLES_PER_BIT with a "+" suffix to shift the odd-numbered edge to the opposite
edges.
Implement SCLK_STUTTER mechanism so the SCL like is not a perfect sequence, by introducing fixed, random half-edge delays.


