name: docs

on:
  push:
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      pandoc:   ${{ steps.detect.outputs.pandoc }}
      asciidoc: ${{ steps.detect.outputs.asciidoc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Detect documentation method
        id: detect
        uses: dlmiles/tt-gds-action/detect@tt05

  docs:
    runs-on: ubuntu-latest
    needs: detect
    env:
      PANDOC: ${{ needs.detect.outputs.pandoc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build pandocs docs
        uses: TinyTapeout/tt-gds-action/docs@tt05

  pandoc:
    runs-on: ubuntu-latest
    if: needs.detect.outputs.pandoc
    needs: detect
    env:
      PANDOC: ${{ needs.detect.outputs.pandoc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build pandocs docs
        #uses: TinyTapeout/tt-gds-action/docs@tt05
        uses: dlmiles/tt-gds-action/docs-pandoc@tt05

  asciidoc:
    runs-on: ubuntu-latest
    if: needs.detect.outputs.asciidoc
    needs: detect
    env:
      ASCIIDOC: ${{ needs.detect.outputs.asciidoc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build asciidoc docs
        #uses: TinyTapeout/tt-gds-action/docs-asciidoc@tt05
        uses: dlmiles/tt-gds-action/docs-asciidoc@tt05

  artifact:
    runs-on: ubuntu-latest
    needs:		# it needs EITHER of these not both (trying if:)
      - pandoc
      - asciidoc
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - name: Build asciidoc docs
        #uses: TinyTapeout/tt-gds-action/docs-artifact@tt05
        uses: dlmiles/tt-gds-action/docs-artifact@tt05
    