name: gds

on:
  push:
  workflow_dispatch:

env:
  JOBS_eqy_test: false

jobs:

  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: patch
        run: |
          cd src

          ./check_verilog_production.sh || true

          echo "### Temporary patch remove before production and signoff"
          echo "### For local simulation these top level signal are used for testing the I2C bus"
          echo "### This patch removes the signals so the verilog is ready for production use"

          ./check_verilog_production.sh patch patch_synthesis quiet

          echo ""
          echo "### This now validates the values inside verilog are production system values or halts the CI"

          ./check_verilog_production.sh

      - name: Build GDS
        uses: dlmiles/tt-gds-action@tt05


  gl_test:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: GL test
        #uses: TinyTapeout/tt-gds-action/gl_test@tt05
        uses: dlmiles/tt-gds-action/gl_test@tt05
        with:
          RANDOM_POLICY:	random


  eqy_test:
    if: ${{ github.event_name == 'eqy_test' }}  # ${{ env.JOBS_eqy_test == 'true' }}
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: eqy test
        #uses: TinyTapeout/tt-gds-action/eqy_test@tt05
        uses: dlmiles/tt-gds-action/eqy_test@tt05


