name: viewer

on:
  workflow_dispatch:
  workflow_run:
    workflows: [gds]
    types:
      - completed

jobs:
  viewer:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dlmiles/tt-gds-action/viewer@tt05
        with:
          # Need to explicitly pass as input.token into composite action
          token: ${{ secrets.GITHUB_TOKEN }}
